/* Prism Path (original): rotate mirrors so the light beam touches every diamond.
   Levels are generated by walking the beam first and placing mirrors along its path,
   so every level is solvable by construction. Time attack: clear as many as you can. */
import { c, W, H, TAU, S, rnd, hap, sfx, tone, burst, end } from '../core.js';

const DX = [1, 0, -1, 0], DY = [0, 1, 0, -1];   // 0 right, 1 down, 2 left, 3 up
const R0 = [3, 2, 1, 0];                        // '/' mirror reflection of each direction
const R1 = [1, 0, 3, 2];                        // '\' mirror reflection
const size = L => L < 3 ? 4 : L < 6 ? 5 : L < 10 ? 6 : 7;
const shuffle = a => { for (let i = a.length - 1; i > 0; i--) { const j = rnd(i + 1); [a[i], a[j]] = [a[j], a[i]]; } return a; };
const MAXT = 90;

export const prism = {
  ctl: 'none',
  init() { this.L = 1; this.tl = 75; this.lock = 0; this.flash = 0; this.msg = ''; this.moved = 0; this.gen(1); },

  /* Follow the beam through mirror layout m. Returns polyline points (cell coords) and the lit cell set. */
  trace(m) {
    const N = this.N, pts = [[-.5, this.er]], lit = new Set();
    let x = 0, y = this.er, d = 0, n = 0;
    while (x >= 0 && x < N && y >= 0 && y < N && n++ < 400) {
      const i = y * N + x; lit.add(i);
      if (m[i] >= 0) d = (m[i] == 0 ? R0 : R1)[d];
      pts.push([x, y]); x += DX[d]; y += DY[d];
    }
    pts.push([x - DX[d] * .5, y - DY[d] * .5]);
    return { pts, lit };
  },
  solved(m, tg) { const { lit } = this.trace(m); return tg.every(i => lit.has(i)); },

  gen(L, depth) {
    const N = size(L); this.N = N;
    for (let tries = 0; tries < 400; tries++) {
      const er = rnd(N), m = Array(N * N).fill(-1), seen = new Set();
      const want = Math.min(2 + Math.floor(L * .7), Math.floor(N * N * .42));
      this.er = er;
      let x = 0, y = er, d = 0, n = 0, placed = 0;
      while (x >= 0 && x < N && y >= 0 && y < N && n++ < N * N * 2) {
        const i = y * N + x;
        if (m[i] < 0 && !seen.has(i) && placed < want && Math.random() < (n < 2 ? .2 : .5)) { m[i] = rnd(2); placed++; }
        seen.add(i);
        if (m[i] >= 0) d = (m[i] == 0 ? R0 : R1)[d];
        x += DX[d]; y += DY[d];
      }
      if (placed < Math.min(want, 2)) continue;
      const sol = m.slice(), { lit } = this.trace(sol);
      let ok = true; for (const i of seen) if (!lit.has(i)) { ok = false; break; }
      if (!ok) continue;
      const T = Math.min(2 + Math.floor(L / 2), 6), cand = shuffle([...seen].filter(i => sol[i] < 0));
      if (cand.length < T) continue;
      const tg = cand.slice(0, T);
      /* decoy mirrors off the solution path */
      const free = shuffle([...Array(N * N).keys()].filter(i => !lit.has(i) && sol[i] < 0));
      for (let k = 0; k < Math.min(Math.floor(L / 2), N, free.length); k++) sol[free[k]] = rnd(2);
      if (!this.solved(sol, tg)) continue;
      /* scramble: flip mirrors until the puzzle is not already solved */
      let m2 = null;
      for (let t = 0; t < 30 && !m2; t++) {
        const q = sol.slice(); for (let i = 0; i < q.length; i++) if (q[i] >= 0 && Math.random() < .7) q[i] ^= 1;
        if (!this.solved(q, tg)) m2 = q;
      }
      if (!m2) continue;
      this.m = m2; this.sol = sol; this.tg = tg;
      this.ang = m2.map(v => v < 0 ? 0 : v ? Math.PI / 4 : -Math.PI / 4);
      this.tr = this.trace(m2); this.prev = new Set(tg.filter(i => this.tr.lit.has(i)));
      this.cs = Math.floor(320 / N); this.ox = Math.floor((W - this.cs * N) / 2); this.oy = Math.floor(108 + (320 - this.cs * N) / 2);
      return;
    }
    if (!depth) return this.gen(1, 1);   // safety net, practically never reached
  },

  click(x, y) {
    if (S.over || this.lock) return;
    const N = this.N, cx = Math.floor((x - this.ox) / this.cs), cy = Math.floor((y - this.oy) / this.cs);
    if (x < this.ox || y < this.oy || cx < 0 || cy < 0 || cx >= N || cy >= N) return;
    const i = cy * N + cx; if (this.m[i] < 0) return;
    this.m[i] ^= 1; this.moved = 1; sfx('rot'); this.refresh();
  },
  cellXY(i) { return [this.ox + (i % this.N + .5) * this.cs, this.oy + (Math.floor(i / this.N) + .5) * this.cs]; },
  refresh() {
    const tr = this.trace(this.m); this.tr = tr;
    for (const i of this.tg) {
      if (tr.lit.has(i)) {
        if (!this.prev.has(i)) {
          this.prev.add(i); const [x, y] = this.cellXY(i);
          burst(x, y, ['#ffc83d', '#fff3b8'], 8, 2); tone(520 + 130 * this.prev.size, .16, 'triangle', .14); hap('light');
        }
      } else this.prev.delete(i);
    }
    if (this.tg.every(i => tr.lit.has(i))) this.solve();
  },
  solve() {
    this.lock = 1; const add = 100 + 25 * this.L;
    S.score += add; this.tl = Math.min(MAXT, this.tl + 6); this.flash = 1.3; this.msg = 'Level ' + this.L + ' cleared  +' + add;
    sfx('win'); hap('success');
    for (const i of this.tg) { const [x, y] = this.cellXY(i); burst(x, y, ['#ffc83d', '#fff3b8', '#5cf0ff'], 14, 3); }
    setTimeout(() => { if (S.cur !== prism || S.over) return; this.L++; this.gen(this.L); this.lock = 0; this.moved = 1; }, 900);
  },

  tick(f, dt) {
    const s = dt / 1000;
    if (!this.lock) this.tl -= s;
    if (this.flash > 0) this.flash -= s;
    for (let i = 0; i < this.m.length; i++) {
      if (this.m[i] < 0) continue;
      const t = this.m[i] ? Math.PI / 4 : -Math.PI / 4;
      this.ang[i] += (t - this.ang[i]) * Math.min(1, .3 * f);
    }
    if (this.tl <= 0) { this.tl = 0; end('Time is up'); }
  },

  draw() {
    const T = performance.now(), N = this.N, cs = this.cs, ox = this.ox, oy = this.oy;
    const g = c.createLinearGradient(0, 0, 0, H); g.addColorStop(0, '#1b2a63'); g.addColorStop(1, '#0e0b2e');
    c.fillStyle = g; c.fillRect(0, 0, W, H);
    c.fillStyle = '#fff7e6';
    for (let i = 0; i < 28; i++) { c.globalAlpha = .15 + .3 * Math.abs(Math.sin(T * .0008 * (1 + i % 3) + i)); c.fillRect((i * 97) % W, (i * 61 + i * i * 5) % H, 1.6, 1.6); }
    c.globalAlpha = 1;
    /* HUD */
    c.textAlign = 'left'; c.font = '700 20px Fredoka,sans-serif'; c.fillStyle = '#fff7e6'; c.fillText('Level ' + this.L, 25, 52);
    c.textAlign = 'right'; c.fillStyle = this.tl < 10 ? '#ff6b4a' : '#fff7e6'; c.fillText(Math.ceil(this.tl) + 's', 335, 52);
    c.fillStyle = '#38308a'; c.beginPath(); c.roundRect(25, 64, 310, 8, 4); c.fill();
    c.fillStyle = this.tl < 10 ? '#ff6b4a' : '#5cf0ff'; c.beginPath(); c.roundRect(25, 64, Math.max(0, 310 * Math.min(1, this.tl / MAXT)), 8, 4); c.fill();
    /* cells */
    for (let i = 0; i < N * N; i++) {
      const x = ox + (i % N) * cs, y = oy + Math.floor(i / N) * cs, mir = this.m[i] >= 0;
      c.beginPath(); c.roundRect(x + 2, y + 2, cs - 4, cs - 4, Math.min(10, cs / 6));
      c.fillStyle = mir ? 'rgba(130,110,255,.16)' : 'rgba(255,255,255,.045)'; c.fill();
      c.strokeStyle = 'rgba(169,163,217,.16)'; c.lineWidth = 1; c.stroke();
    }
    /* emitter + beam */
    const ey = oy + (this.er + .5) * cs;
    c.fillStyle = '#ffc83d'; c.beginPath(); c.roundRect(ox - 26, ey - 9, 16, 18, 4); c.fill();
    c.fillStyle = '#fff3b8'; c.beginPath(); c.moveTo(ox - 10, ey - 6); c.lineTo(ox, ey); c.lineTo(ox - 10, ey + 6); c.fill();
    const P = this.tr.pts.map(p => [ox + (p[0] + .5) * cs, oy + (p[1] + .5) * cs]), col = this.lock ? '#ffd95a' : '#5cf0ff';
    c.save(); c.lineJoin = 'round'; c.lineCap = 'round';
    c.shadowColor = col; c.shadowBlur = 16; c.strokeStyle = col; c.globalAlpha = .9; c.lineWidth = Math.max(4, cs / 13);
    c.beginPath(); c.moveTo(ox - 10, P[0][1]); P.forEach(p => c.lineTo(p[0], p[1])); c.stroke();
    c.globalAlpha = 1; c.shadowBlur = 0; c.strokeStyle = '#f2ffff'; c.lineWidth = Math.max(1.5, cs / 34); c.stroke();
    c.setLineDash([2, 26]); c.lineDashOffset = -(T * .06); c.strokeStyle = '#fff'; c.lineWidth = 3; c.stroke();
    c.restore();
    /* targets */
    for (const i of this.tg) {
      const [x, y] = this.cellXY(i), lit = this.tr.lit.has(i), r = cs * .27;
      const dia = k => { c.beginPath(); c.moveTo(0, -r * k * 1.15); c.lineTo(r * k, 0); c.lineTo(0, r * k * 1.15); c.lineTo(-r * k, 0); c.closePath(); };
      c.save(); c.translate(x, y);
      if (lit) {
        const pu = 1 + Math.sin(T * .008) * .08;
        c.shadowColor = '#ffc83d'; c.shadowBlur = 18; c.fillStyle = '#ffc83d'; c.scale(pu, pu); dia(1); c.fill();
        c.shadowBlur = 0; c.fillStyle = '#fff3b8'; dia(.5); c.fill();
        c.strokeStyle = 'rgba(255,200,61,.5)'; c.lineWidth = 2; c.beginPath(); c.arc(0, 0, r * 1.5 + Math.sin(T * .006) * 2, 0, TAU); c.stroke();
      } else {
        c.fillStyle = 'rgba(138,127,216,.18)'; dia(1); c.fill(); c.strokeStyle = '#8a7fd8'; c.lineWidth = 3; c.stroke();
      }
      c.restore();
    }
    /* mirrors */
    for (let i = 0; i < N * N; i++) {
      if (this.m[i] < 0) continue;
      const [x, y] = this.cellXY(i), L = cs * .4;
      c.save(); c.translate(x, y); c.rotate(this.ang[i]); c.lineCap = 'round';
      c.strokeStyle = '#2a2166'; c.lineWidth = cs * .14 + 3; c.beginPath(); c.moveTo(-L, 0); c.lineTo(L, 0); c.stroke();
      const gr = c.createLinearGradient(0, -cs * .06, 0, cs * .06); gr.addColorStop(0, '#ffffff'); gr.addColorStop(.5, '#b9b2ff'); gr.addColorStop(1, '#6f63d8');
      c.strokeStyle = gr; c.lineWidth = cs * .1; c.beginPath(); c.moveTo(-L, 0); c.lineTo(L, 0); c.stroke();
      c.fillStyle = '#fff'; c.beginPath(); c.arc(0, 0, cs * .045, 0, TAU); c.fill();
      c.restore();
    }
    /* messages */
    c.textAlign = 'center';
    if (this.flash > 0) { c.globalAlpha = Math.min(1, this.flash * 1.5); c.font = '700 24px Fredoka,sans-serif'; c.fillStyle = '#ffc83d'; c.fillText(this.msg, W / 2, 96); c.globalAlpha = 1; }
    if (this.L == 1 && !this.moved) { c.font = '600 15px Fredoka,sans-serif'; c.fillStyle = '#fff7e6'; c.fillText('Tap a mirror to turn it.', W / 2, 452); c.fillStyle = '#ffc83d'; c.fillText('Light every diamond before time runs out.', W / 2, 472); }
  },
};
